on:
  pull_request:
    branches:
      - master
      - main
      - release-**
      - "*"
jobs:
  swagger_editor_validator_remote:
    runs-on: ubuntu-latest
    name: Validate the swagger with redocly

    steps:
      - uses: actions/checkout@v2
      - name: Validate OpenAPI definition with redocly
        run: |
          cd scripts/navigation-levels
          go run main.go --max=$MAX_LEVELS

