on:
  pull_request:
    branches:
      - master
      - release-**
      - document-process-to-generate-the-oas
jobs:
  test_swagger_editor_validator_remote:
    runs-on: ubuntu-latest
    name: Validate the swagger with redocly cli

    steps:
      - uses: actions/checkout@v2
      - name: Validate OpenAPI definition with redocly
